/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
W0312 18:33:43.335859 23172488814912 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3374687 closing signal SIGTERM
W0312 18:33:43.335875 22494735802688 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3952732 closing signal SIGTERM
W0312 18:33:43.336210 23172488814912 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3374688 closing signal SIGTERM
W0312 18:33:43.336201 22494735802688 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3952733 closing signal SIGTERM
W0312 18:33:43.336804 22954412691776 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 2183606 closing signal SIGTERM
W0312 18:33:43.337151 22954412691776 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 2183607 closing signal SIGTERM
W0312 18:33:43.336549 23432571924800 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1618830 closing signal SIGTERM
W0312 18:33:43.337167 22478669037888 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 2665134 closing signal SIGTERM
E0312 18:33:43.338054 23432571924800 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 1618828) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
E0312 18:33:43.338670 22478669037888 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 2665132) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
E0312 18:33:43.339563 23172488814912 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 3374686) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
E0312 18:33:43.339544 22494735802688 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 3952731) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
E0312 18:33:43.340499 22954412691776 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 2183605) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
/work/09816/wertyuui345/ls6/env/VCMamba/bin/python: can't open file '/scratch/09816/wertyuui345/ls6/VCMamba/VCMamba/segmentation/train.py': [Errno 2] No such file or directory
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_18:33:43
  host      : c317-002.ls6.tacc.utexas.edu
  rank      : 16 (local_rank: 1)
  exitcode  : 2 (pid: 1618829)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c317-002.ls6.tacc.utexas.edu
  rank      : 15 (local_rank: 0)
  exitcode  : 2 (pid: 1618828)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c317-003.ls6.tacc.utexas.edu
  rank      : 18 (local_rank: 0)
  exitcode  : 2 (pid: 2183605)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c315-005.ls6.tacc.utexas.edu
  rank      : 6 (local_rank: 0)
  exitcode  : 2 (pid: 3952731)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_18:33:43
  host      : c316-007.ls6.tacc.utexas.edu
  rank      : 13 (local_rank: 1)
  exitcode  : 2 (pid: 2665133)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c316-007.ls6.tacc.utexas.edu
  rank      : 12 (local_rank: 0)
  exitcode  : 2 (pid: 2665132)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c305-002.ls6.tacc.utexas.edu
  rank      : 3 (local_rank: 0)
  exitcode  : 2 (pid: 3374686)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
E0312 18:33:43.432332 23228241297728 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 32715) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
E0312 18:33:43.437728 23449895641408 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 2834533) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_18:33:43
  host      : c303-004.ls6.tacc.utexas.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 32716)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-03-12_18:33:43
  host      : c303-004.ls6.tacc.utexas.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 32719)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c303-004.ls6.tacc.utexas.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 32715)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
E0312 18:33:43.441947 23438181798208 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 2800781) of binary: /work/09816/wertyuui345/ls6/env/VCMamba/bin/python
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    return arg(*args, **kwargs)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_18:33:43
  host      : c317-015.ls6.tacc.utexas.edu
  rank      : 22 (local_rank: 1)
  exitcode  : 2 (pid: 2834534)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-03-12_18:33:43
  host      : c317-015.ls6.tacc.utexas.edu
  rank      : 23 (local_rank: 2)
  exitcode  : 2 (pid: 2834535)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c317-015.ls6.tacc.utexas.edu
  rank      : 21 (local_rank: 0)
  exitcode  : 2 (pid: 2834533)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    launch(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/09816/wertyuui345/ls6/env/VCMamba/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_18:33:43
  host      : c315-011.ls6.tacc.utexas.edu
  rank      : 10 (local_rank: 1)
  exitcode  : 2 (pid: 2800782)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-03-12_18:33:43
  host      : c315-011.ls6.tacc.utexas.edu
  rank      : 11 (local_rank: 2)
  exitcode  : 2 (pid: 2800783)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_18:33:43
  host      : c315-011.ls6.tacc.utexas.edu
  rank      : 9 (local_rank: 0)
  exitcode  : 2 (pid: 2800781)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
